### ISSUE TITLE
Generation fails with multi-byte heading level-2 and up

### ISSUE THREAD

**Issue by kulikala** [magidoc-org/magidoc#174]
### Describe the bug

After having updates to `carbon-multi-page@2.14.4`, generation of documents always fails.
As noted in the error message, the error occurs in headings that contain multi-byte characters in the Markdown.
This does not occur in level 1 heading, but does occur in level 2 and above.

### Reproduction

`schema.graphql`
```graphql
type Query {
  """
  ## ⌘
  """
  me: ID
}
```

`magidoc.mjs`
```javascript
/**
 * @type {import("@magidoc/cli").MagidocConfiguration}
 */
const config = {
  introspection: {
    type: 'sdl',
    paths: [
      'schema.graphql'
    ]
  },

  website: {
    template: 'carbon-multi-page',
    output: '.output/public/schema-docs'
  }
}

export default config
```

### Logs

```shell
$ npx magidoc generate
✔ Determine tmp directories [0.0s]
✔ Select Package Manager [0.3s]
  › Selected npm
    ⚠️ This package manager is not well supported yet.
    ⚠️ It is recommended to install pnpm instead.
↓ Template already unzipped. [SKIPPED]
↓ Template already unzipped [SKIPPED]
✔ Install dependencies [5s]
✔ Resolving template configuration [0.0s]
  › Found 8 supported keys
    Target schema location: ./src/_schema.json
✔ Load GraphQL Schema [0.0s]
✔ Write variables file [0.0s]
✖ Build template
◼ Move output
Command 'npm' failed with status 1 when executed in directory /var/folders/4d/5pyx_0k52vv0r0xlwd1vs66c0000gn/T/carbon-multi-page@2.14.4

---- Program Output----

> @magidoc/starter-carbon-multi-page@2.14.4 build
> vite build

vite v3.2.4 building for production...
transforming...
✓ 443 modules transformed.
1:20:25 [vite-plugin-svelte] dom compile done.
package                                 files    time      avg
@magidoc/starter-carbon-multi-page        163   2.54s   15.6ms
rendering chunks...
vite v3.2.4 building SSR bundle for production...
transforming...
"GraphQLInterfaceType" and "GraphQLObjectType" are imported from external module "graphql" but never used in "src/lib/components/tags/TypeTag.svelte", "src/lib/components/common/text/TypeLink.svelte", "src/lib/model.ts", "src/lib/components/tags/NullableTag.svelte" and "src/routes/types/[type]/+page.svelte".
✓ 260 modules transformed.
1:20:28 [vite-plugin-svelte] ssr compile done.
package                                 files    time     avg
@magidoc/starter-carbon-multi-page        163   0.52s   3.2ms
Generated an empty chunk: "hooks"
rendering chunks...
.svelte-kit/output/server/vite-manifest.json                                           6.03 KiB
.svelte-kit/output/server/index.js                                                     73.29 KiB
.svelte-kit/output/server/entries/pages/_layout.svelte.js                              94.96 KiB
.svelte-kit/output/server/entries/pages/_error.svelte.js                               1.10 KiB
.svelte-kit/output/server/entries/pages/_page.ts.js                                    0.22 KiB
.svelte-kit/output/server/entries/pages/_...page_/_page.svelte.js                      0.88 KiB
.svelte-kit/output/server/entries/pages/_...page_/_page.ts.js                          0.38 KiB
.svelte-kit/output/server/entries/pages/mutations/_mutation_/_page.svelte.js           0.99 KiB
.svelte-kit/output/server/entries/pages/mutations/_mutation_/_page.ts.js               0.53 KiB
.svelte-kit/output/server/entries/pages/queries/_query_/_page.svelte.js                0.95 KiB
.svelte-kit/output/server/entries/pages/queries/_query_/_page.ts.js                    0.51 KiB
.svelte-kit/output/server/entries/pages/subscriptions/_subscription_/_page.svelte.js   1.00 KiB
.svelte-kit/output/server/entries/pages/subscriptions/_subscription_/_page.ts.js       0.56 KiB
.svelte-kit/output/server/entries/pages/types/_type_/_page.svelte.js                   23.27 KiB
.svelte-kit/output/server/entries/pages/types/_type_/_page.ts.js                       0.58 KiB
.svelte-kit/output/server/chunks/paths.js                                              0.17 KiB
.svelte-kit/output/server/chunks/index.js                                              9.93 KiB
.svelte-kit/output/server/chunks/ssr.js                                                0.12 KiB
.svelte-kit/output/server/chunks/index2.js                                             1.17 KiB
.svelte-kit/output/server/chunks/index3.js                                             2.27 KiB
.svelte-kit/output/server/chunks/ChevronDown.js                                        5.50 KiB
.svelte-kit/output/server/chunks/variables.js                                          0.26 KiB
.svelte-kit/output/server/chunks/stores.js                                             1.00 KiB
.svelte-kit/output/server/chunks/pages.js                                              3.59 KiB
.svelte-kit/output/server/chunks/index4.js                                             16.22 KiB
.svelte-kit/output/server/chunks/model.js                                              32.80 KiB
.svelte-kit/output/server/chunks/Button.js                                             6.82 KiB
.svelte-kit/output/server/chunks/PreviousNextPage.js                                   57.67 KiB
.svelte-kit/output/server/chunks/FieldDetails.js                                       18.49 KiB
.svelte-kit/output/server/chunks/ArgsList.js                                           7.18 KiB
.svelte-kit/output/server/chunks/hooks.js                                              0.00 KiB
  301 / -> /introduction/welcome
file:///private/var/folders/4d/5pyx_0k52vv0r0xlwd1vs66c0000gn/T/carbon-multi-page@2.14.4/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:30
                                throw new Error(format(details));
                                      ^

Error: The following pages contain links to /queries/me#%E2%8C%98, but no element with id="%E2%8C%98" exists on /queries/me:
  - /queries/me
    at file:///private/var/folders/4d/5pyx_0k52vv0r0xlwd1vs66c0000gn/T/carbon-multi-page@2.14.4/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:30:11
    at prerender (file:///private/var/folders/4d/5pyx_0k52vv0r0xlwd1vs66c0000gn/T/carbon-multi-page@2.14.4/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:421:4)
[vite-plugin-svelte-kit] Prerendering failed with code 1
error during build:
Error: Prerendering failed with code 1
    at ChildProcess.<anonymous> (file:///private/var/folders/4d/5pyx_0k52vv0r0xlwd1vs66c0000gn/T/carbon-multi-page@2.14.4/node_modules/@sveltejs/kit/src/exports/vite/index.js:462:15)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)


For a more detailed output, run with --stacktrace
```

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 784.23 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.15.1 - ~/.nodebrew/current/bin/node
    npm: 8.11.0 - ~/.nodebrew/current/bin/npm
  Browsers:
    Chrome: 107.0.5304.121
    Edge: 107.0.1418.56
    Firefox: 107.0
    Safari: 16.1
```
```


### Severity

Blocking all usage of Magidoc

**Comment by pelletier197** [comment]
Thanks for raising the issue. Version 2.14.4 only bumped some dependencies. This must be a regression (or an improvement) in Svelte-Kit. 

I'll have a look at it as soon as I get some time.

**Comment by kulikala** [comment]
Thank you for taking the time.
For the time being, I will deal with this issue by setting the following configuration:

`magidoc.mjs`

```javascript
/**
 * @type {import("@magidoc/cli").MagidocConfiguration}
 */
const config = {
  introspection: {
    // ...
  },
  website: {
    template: 'carbon-multi-page',
    templateVersion: '2.14.3'
  }
}

export default config
```

**Comment by pelletier197** [comment]
Hi @kulikala. I've just released a new version with bumped dependencies. It seems fine on my side now, so this must have been a bug in svelte-kit. Feel free to re-open if you still face the issue.

**Comment by kulikala** [comment]
Hi @pelletier197 , thanks for your quick work in resolving this issue.
After upgraded to `2.14.5`, it was generated without any problems!
