### ISSUE TITLE
logo with siteRoot not working

### ISSUE THREAD

**Issue by mostafa-rz** [magidoc-org/magidoc#205]
### Describe the bug

Hi,
I used the fauna example to create my docs. The only difference is using the siteRoot. It throws an exception during the docs generation.

### Reproduction

```
import {fileURLToPath} from 'url'
import path from 'path'

function relativePath(target) {
    return path.join(path.dirname(fileURLToPath(import.meta.url)), target)
}

function markdown(string) {
    // Takes the first indent and trims that length from everywhere.
    // Markdown templates don't like the extra space at the beginning.
    const target = string[0]
    const trimSize = /^\s+/.exec(string)[0].length
    return target
        .split('\n')
        .map((line) => line.substr(trimSize - 1))
        .join('\n')
}

export default {
    introspection: {
        type: 'sdl',
        paths: ['./storage/app/lighthouse-schema.graphql']
    },
    website: {
        template: 'carbon-multi-page',
        output: './public/docs/',
        staticAssets: relativePath('public/assets'),
        options: {
            siteRoot: '/docs',
            appTitle: 'my GraphQL API',
            appLogo: '/logo.png',
            appFavicon: '/logo.png',
            siteMeta: {
                description: "my GraphQL API documentation.",
            },
            pages: [
                {
                    title: 'Welcome',
                    content: markdown`
                        # 👋 Hi
                        Welcome to my GraphQL API documentation.
                      `,
                }
            ],
        },
    },
}
```

### Logs

```shell
✓ built in 44.87s
  301 /docs -> /docs/welcome
file:///tmp/carbon-multi-page@3.6.0/node_modules/.pnpm/@sveltejs+kit@1.14.0_svelte@3.57.0_vite@4.2.1/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:53
                                        throw new Error(format(details));
                                              ^

Error: 404 /logo.png does not begin with `base`, which is configured in `paths.base` and can be imported from `$app/paths` - see https://kit.svelte.dev/docs/configuration#paths for more info (linked from /docs/welcome)
    at file:///tmp/carbon-multi-page@3.6.0/node_modules/.pnpm/@sveltejs+kit@1.14.0_svelte@3.57.0_vite@4.2.1/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:53:12
    at visit (file:///tmp/carbon-multi-page@3.6.0/node_modules/.pnpm/@sveltejs+kit@1.14.0_svelte@3.57.0_vite@4.2.1/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:185:4)
    at Object.fn (file:///tmp/carbon-multi-page@3.6.0/node_modules/.pnpm/@sveltejs+kit@1.14.0_svelte@3.57.0_vite@4.2.1/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:175:22)
    at dequeue (file:///tmp/carbon-multi-page@3.6.0/node_modules/.pnpm/@sveltejs+kit@1.14.0_svelte@3.57.0_vite@4.2.1/node_modules/@sveltejs/kit/src/core/postbuild/queue.js:40:42)
    at file:///tmp/carbon-multi-page@3.6.0/node_modules/.pnpm/@sveltejs+kit@1.14.0_svelte@3.57.0_vite@4.2.1/node_modules/@sveltejs/kit/src/core/postbuild/queue.js:49:7
[vite-plugin-sveltekit-compile] Failed with code 1
✓ built in 1m 6s
error during build:
Error: Failed with code 1
    at ChildProcess.<anonymous> (file:///tmp/carbon-multi-page@3.6.0/node_modules/.pnpm/@sveltejs+kit@1.14.0_svelte@3.57.0_vite@4.2.1/node_modules/@sveltejs/kit/src/utils/fork.js:68:13)
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
 ELIFECYCLE  Command failed with exit code 1.
```

### System Info

```shell
System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
    Memory: 4.94 GB / 7.62 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 16.19.1 - /usr/bin/node
    npm: 9.6.4 - /usr/bin/npm
```

### Severity

Annoyance

**Comment by pelletier197** [comment]
Hi @mostafa-rz. Thanks for raising this issue. You should be able to work around this issue by changing your `appLogo` and `appFavicon` to 

```
appLogo: '/docs/logo.png',
appFavicon: '/docs/logo.png',
```

I believe the reason I did not append the base URL to this is because you could decide to use a full URL instead of a static asset (hosting the logo outside the website). I could add some logic to append the base URL in the current refactoring, but this might take a bit of time. I'm rather busy these days.

**Comment by mostafa-rz** [comment]
Thanks @pelletier197 for your response and it is working now.
