### ISSUE TITLE
magidoc generate started failing generating what looks like valid types

### ISSUE THREAD

**Issue by jonny-ras** [magidoc-org/magidoc#265]
### Describe the bug

We've been using Magidoc to great success in Rasayel, but suddenly it started failing on what looks (to me) to be valid types.

From one day to the next our automated deploys stopped working with this error. From when it started failing to the next day, we made no major changes to our GraphQL schema.
```sh
11:23:38 AM: [FAILED] (!) Some chunks are larger than 500 kBs after minification. Consider:
11:23:38 AM: [FAILED] - Using dynamic import() to code-split the application
11:23:38 AM: [FAILED] - Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
11:23:38 AM: [FAILED] - Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
11:23:38 AM: [FAILED] ✓ built in 29.03s
11:23:38 AM: [FAILED]   301 / -> /introduction/welcome
11:23:38 AM: [FAILED] Error: This code block should be unreachable. If you ever receive this exception, it means you have an invalid setup using GraphQL.
11:23:38 AM: [FAILED]     at asTypeSearchResult (file:///tmp/carbon-multi-page@3.6.0/node_modules/@magidoc/plugin-fuse-graphql/build/indexer/graphql/types.js:24:11)
11:23:38 AM: [FAILED]     at file:///tmp/carbon-multi-page@3.6.0/node_modules/@magidoc/plugin-fuse-graphql/build/indexer/indexer.js:78:18
11:23:38 AM: [FAILED]     at Array.forEach (<anonymous>)
11:23:38 AM: [FAILED]     at indexAllTypes (file:///tmp/carbon-multi-page@3.6.0/node_modules/@magidoc/plugin-fuse-graphql/build/indexer/indexer.js:71:40)
11:23:38 AM: [FAILED]     at index (file:///tmp/carbon-multi-page@3.6.0/node_modules/@magidoc/plugin-fuse-graphql/build/indexer/indexer.js:67:5)
11:23:38 AM: [FAILED]     at file:///tmp/carbon-multi-page@3.6.0/.svelte-kit/output/server/entries/pages/_layout.svelte.js:1397:22
11:23:38 AM: [FAILED]     at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
11:23:38 AM: [FAILED]     at async Promise.all (index 0)
11:23:38 AM: [FAILED]     at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
11:23:38 AM: [FAILED]     at async Module.component (file:///tmp/carbon-multi-page@3.6.0/.svelte-kit/output/server/nodes/0.js:4:39)
11:23:38 AM: [FAILED] Error: This code block should be unreachable. If you ever receive this exception, it means you have an invalid setup using GraphQL.
11:23:38 AM: [FAILED]     at asTypeSearchResult (file:///tmp/carbon-multi-page@3.6.0/node_modules/@magidoc/plugin-fuse-graphql/build/indexer/graphql/types.js:24:11)
11:23:38 AM: [FAILED]     at file:///tmp/carbon-multi-page@3.6.0/node_modules/@magidoc/plugin-fuse-graphql/build/indexer/indexer.js:78:18
11:23:38 AM: [FAILED]     at Array.forEach (<anonymous>)
11:23:38 AM: [FAILED]     at indexAllTypes (file:///tmp/carbon-multi-page@3.6.0/node_modules/@magidoc/plugin-fuse-graphql/build/indexer/indexer.js:71:40)
11:23:38 AM: [FAILED]     at index (file:///tmp/carbon-multi-page@3.6.0/node_modules/@magidoc/plugin-fuse-graphql/build/indexer/indexer.js:67:5)
11:23:38 AM: [FAILED]     at file:///tmp/carbon-multi-page@3.6.0/.svelte-kit/output/server/entries/pages/_layout.svelte.js:1397:22
11:23:38 AM: [FAILED]     at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
11:23:38 AM: [FAILED]     at async Promise.all (index 0)
11:23:38 AM: [FAILED]     at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
11:23:38 AM: [FAILED]     at async Module.component (file:///tmp/carbon-multi-page@3.6.0/.svelte-kit/output/server/nodes/0.js:4:39)
11:23:38 AM: [FAILED] file:///tmp/carbon-multi-page@3.6.0/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:53
11:23:38 AM: [FAILED] 					throw new Error(format(details));
11:23:38 AM: [FAILED] 					      ^
11:23:38 AM: [FAILED]
11:23:38 AM: [FAILED] Error: 500 /introduction/welcome (linked from /)
11:23:38 AM: [FAILED]     at file:///tmp/carbon-multi-page@3.6.0/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:53:12
11:23:38 AM: [FAILED]     at save (file:///tmp/carbon-multi-page@3.6.0/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:359:4)
11:23:38 AM: [FAILED]     at visit (file:///tmp/carbon-multi-page@3.6.0/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:211:3)
```

I then tried to reproduce it locally, and started logging the types it fails on to see what has gone wrong, it fails parsing the very first type.
```sh
(!) Some chunks are larger than 500 kBs after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
✓ built in 21.49s
  301 / -> /introduction/welcome
Indexing type GraphQLInputObjectType {
  name: 'AbmInputObject',
  description: undefined,
  extensions: [Object: null prototype] {},
  astNode: {
    kind: 'InputObjectTypeDefinition',
    description: undefined,
    name: { kind: 'Name', value: 'AbmInputObject', loc: [Location] },
    directives: [],
    fields: [ [Object] ],
    loc: Location {
      start: 126,
      end: 170,
      startToken: [Token],
      endToken: [Token],
      source: [Source]
    }
  },
  extensionASTNodes: [],
  _fields: [Object: null prototype] {
    messageId: {
      name: 'messageId',
      description: undefined,
      type: [GraphQLScalarType],
      defaultValue: undefined,
      deprecationReason: undefined,
      extensions: [Object: null prototype] {},
      astNode: [Object]
    }
  }
}
Error: This code block should be unreachable. Type is AbmInputObject. If you ever receive this exception, it means you have an invalid setup using GraphQL.
    at asTypeSearchResult (file:///private/var/folders/dt/gnkdtyg517s7k59843dp47l00000gn/T/carbon-multi-page@4.1.0/node_modules/@magidoc/plugin-fuse-graphql/build/indexer/graphql/types.js:24:11)
    at file:///private/var/folders/dt/gnkdtyg517s7k59843dp47l00000gn/T/carbon-multi-page@4.1.0/node_modules/@magidoc/plugin-fuse-graphql/build/indexer/indexer.js:79:18
    at Array.forEach (<anonymous>)
    at indexAllTypes (file:///private/var/folders/dt/gnkdtyg517s7k59843dp47l00000gn/T/carbon-multi-page@4.1.0/node_modules/@magidoc/plugin-fuse-graphql/build/indexer/indexer.js:71:40)
    at index (file:///private/var/folders/dt/gnkdtyg517s7k59843dp47l00000gn/T/carbon-multi-page@4.1.0/node_modules/@magidoc/plugin-fuse-graphql/build/indexer/indexer.js:67:5)
    at file:///private/var/folders/dt/gnkdtyg517s7k59843dp47l00000gn/T/carbon-multi-page@4.1.0/.svelte-kit/output/server/entries/pages/_layout.svelte.js:1397:22
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async Module.component (file:///private/var/folders/dt/gnkdtyg517s7k59843dp47l00000gn/T/carbon-multi-page@4.1.0/.svelte-kit/output/server/nodes/0.js:4:39)
    at async Promise.all (index 0)

node:internal/event_target:1083
  process.nextTick(() => { throw err; });
                           ^
Error: 500 /introduction/welcome (linked from /)
To suppress or handle this error, implement `handleHttpError` in https://kit.svelte.dev/docs/configuration#prerender
    at file:///private/var/folders/dt/gnkdtyg517s7k59843dp47l00000gn/T/carbon-multi-page@4.1.0/node_modules/@sveltejs/kit/src/core/config/options.js:211:13
    at file:///private/var/folders/dt/gnkdtyg517s7k59843dp47l00000gn/T/carbon-multi-page@4.1.0/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:64:25
    at save (file:///private/var/folders/dt/gnkdtyg517s7k59843dp47l00000gn/T/carbon-multi-page@4.1.0/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:403:4)
    at visit (file:///private/var/folders/dt/gnkdtyg517s7k59843dp47l00000gn/T/carbon-multi-page@4.1.0/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:236:3)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:326:10)
    at [kOnMessage] (node:internal/worker:337:37)
    at MessagePort.<anonymous> (node:internal/worker:232:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:807:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)

Node.js v20.8.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.


For a more detailed output, run with --stacktrace
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I've bumped the package from `3.6.0` to `4.1.0` locally but I'm still getting the same error.

### Reproduction

I've been able to reproduce it locally by using the introspection query against our API: `https://api.rasayel.io/api/graphql` locally, but I can't figure out what's wrong with it, it looks correct to me.

I'm seeing this in production (Netlify) and on my local Mac.

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 116.59 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.8.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 10.1.0 - /opt/homebrew/bin/npm
    Watchman: 2023.10.02.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 117.0.5938.149
    Edge: 117.0.2045.55
    Safari: 16.5.2
```
```


### Severity

Blocking all usage of Magidoc

**Comment by pelletier197** [comment]
Hi, thank you for raising this. I'll try to have a look asap. 

I see you're using node 20, did you upgrade your node version recently ? Do you think that could be the source of the problem ?

Obviously it should run on node 20 but I've seen some errors occur on various versions of node in the past.

**Comment by pelletier197** [comment]
Thanks for the details. Would it be possible to provide your schema, or at least a schema that allows to reproduce the issue ? I have tried reproducing with the few schema I have available and I'm not able to reproduce with any of them. 

Thanks for your help.

**Comment by jonny-ras** [comment]
@pelletier197 absolutely! https://studio.apollographql.com/public/rasayel-public-api-on1kuq/variant/current/schema/sdl

This is our public API schema

**Comment by jonny-ras** [comment]
Hey @pelletier197 just a gentle nudge on this, we still can't build our schema so our docs are quite out of date, I'd love to get it back up and running again.

**Comment by jonny-ras** [comment]
Completely understand @pelletier197 - I'm happy to take a look as well but unfortunately I've become quite stumped on it. 

Appreciate your time on this 👍

**Comment by pelletier197** [comment]
Can you try upgrading to 4.1.1 ? I've been able to generate the website successfully with that version by copying that raw content from your public schema into a file. 

If that still doesn't work, I would check for what you have installed globally. Namely, is it possible that you forced an outdated [GraphQL JS](https://www.npmjs.com/package/graphql) version on your environment or something like that ?

**Comment by pelletier197** [comment]
Other question, is pnpm installed where you're trying to build docs ? The builder works best when using pnpm rather than npm. If you could try this locally that'd be great.

**Comment by jonny-ras** [comment]
@pelletier197 whatever you changed with 4.1.2 has made it work! Thank you so much for your time on this. I really appreciate it

**Comment by pelletier197** [comment]
Awesome. I guess this is another mistery of the universe. Happy this solved your problem, have a good day!
